//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Inscripcions = new HashSet<Inscripcion>();
        }
    
        public int idCursos { get; set; }
        public System.DateTime FechaIncial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int CupoAct { get; set; }
        public int CupoMax { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int PlanDeEstudio_idPlanDeEstudio { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual PlanDeEstudio PlanDeEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcions { get; set; }
    }
}
