//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int idInscripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Alumno_idAlumno { get; set; }
        public int Usuario_idUsuario { get; set; }
        public int Curso_idCursos { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
