//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListadoAlumnosPorCurso
    {
        public int idCursos { get; set; }
        public string legajo { get; set; }
        public string Dni { get; set; }
        public string apeNom { get; set; }
    }
}
