//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidad;


    public partial class BD_CasaDeLaCiudad : DbContext
    {
        public BD_CasaDeLaCiudad()
            : base("name=BD_CasaDeLaCiudad")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<vw_EmpleadosSinUsuario> vw_EmpleadosSinUsuario { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<PlanDeEstudio> PlanDeEstudios { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<Inscripcion> Inscripcions { get; set; }
        public virtual DbSet<vw_EmpleadoProfesor> vw_EmpleadoProfesor { get; set; }
        public virtual DbSet<vw_CursosConInscripcion> vw_CursosConInscripcion { get; set; }
        public virtual DbSet<vw_CursoPlanDeEstudio> vw_CursoPlanDeEstudio { get; set; }
    }
}
